/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface GalleryItem {
  'id' : bigint,
  'title' : string,
  'imageBlob' : ExternalBlob,
  'createdAt' : Time,
  'description' : string,
  'category' : string,
}
export interface ResearchPaper {
  'id' : bigint,
  'title' : string,
  'pdfBlob' : ExternalBlob,
  'createdAt' : Time,
  'tags' : Array<string>,
  'description' : string,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WritingEntry {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'createdAt' : Time,
  'tags' : Array<string>,
  'excerpt' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGalleryItem' : ActorMethod<
    [string, string, string, ExternalBlob],
    undefined
  >,
  'addResearchPaper' : ActorMethod<
    [string, string, Array<string>, ExternalBlob],
    undefined
  >,
  'addWritingEntry' : ActorMethod<
    [string, string, string, Array<string>],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteGalleryItem' : ActorMethod<[bigint], undefined>,
  'deleteResearchPaper' : ActorMethod<[bigint], undefined>,
  'deleteWritingEntry' : ActorMethod<[bigint], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'listResearchPapers' : ActorMethod<[], Array<ResearchPaper>>,
  'listWritingEntries' : ActorMethod<[], Array<WritingEntry>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];